### PR TITLE
feat: Identity popover

### PR DESCRIPTION
**Pull request by RemiBardon**
TODO:

- [x] Static UI
- [x] Dark mode check
- [x] Localization
- [x] Accessibility
- [x] Dynamic UI
- [x] TCA integration
- [x] ~~Preview app~~
- [x] Integration in the app

What I have:
Screenshot 2022-07-12 at 09 02 15
Screenshot 2022-07-12 at 09 03 14

The design:

Screenshot 2022-07-11 at 22 49 21

### CODE REVIEW

**Comment by RemiBardon** [comment]
For now it's all static.

**Comment by valeriansaliou** [comment]
This is perfectly done, I like it! :)

**Comment by RemiBardon** [comment]
@valeriansaliou What do you mean?

To answer what I understand:
- I'm using the green you already defined ages ago, which is the one used accross the app
- For consistency with the OS and dark mode support:
  - Most labels use no color, which defaults to `.primary` (black/white depending on the theme)
  - The header subtitle and "Government ID" icon use the `.secondary` `Color`
  - The center background color is `Color(nsColor: .windowBackgroundColor)`
  - The separator is a `Divider()`
  - The header and footer have no background color, which means they take the default material background of popovers (which looks gorgeous, but you can't see it in my screenshots because the layers are isolated. Here is a better examples:

Screenshot 2022-07-12 at 10 03 28
Screenshot 2022-07-12 at 10 01 19

**Comment by RemiBardon** [comment]
I disabled all of the help buttons, as I don't know what content should be displayed.

**Comment by valeriansaliou** [comment]
I was speaking about the background colors yes, the other colors perfectly match the design. In the end, I have to say: LGTM, given your last screenshot. Looks gorgeous like that w/ the translucent background! Perfect

**Comment by RemiBardon** [comment]
Hmmm… this looks weird… I have no Idea where it comes from 🤔
https://user-images.githubusercontent.com/37386490/178448268-b6eceb5a-d0ab-4de3-b5a1-be6691c98b8c.mov

**Comment by RemiBardon** [comment]
Let's forget it, it may just be a bug

**Review by nesium — APPROVED** [review]

**Pull request merged**
