### PR TITLE
Add build tools

### PR DESCRIPTION
**Pull request by nesium**
This PR adds the tools needed to generate strings and format code as a separate Swift package. It allows to simply run `make assets` or `make format` without having to manually install any other dependencies. The current version of the build tools is also automatically tracked by spm using the package.resolved file.

### CODE REVIEW

**Review by RemiBardon — APPROVED** [review]
Looks good to me, thank you 🙏🏻

**Comment by RemiBardon** [comment]
I'm sorry I merged your PR 🫢 I was a bit too quick on the taps 🫢

**Comment by nesium** [comment]
That was me. So, no worries

Screenshot 2022-06-12 at 18 23 39
.

**Comment by RemiBardon** [comment]
Oh yeah… I thought I had merged it

**Pull request merged**
