### PR TITLE
chore: Refactor and improve `SettingsFeature`

### PR DESCRIPTION
**Pull request by RemiBardon**
Remove `sindresorhus/Preferences` dependency in favor of SwiftUI `Settings`

Also rename views, fix layout issues and make views more flexible by using some SwiftUI features.

Here is a diff of the changes:

| Before | After | Artboards |
| ------ | ----- | --------- |
| Screenshot 2022-06-24 at 13 58 35 | Screenshot 2022-06-24 at 14 01 06 | Screenshot 2022-06-24 at 14 13 39|
| Screenshot 2022-06-24 at 13 58 54 | Screenshot 2022-06-24 at 14 16 25 | Screenshot 2022-06-24 at 14 14 01|
| Screenshot 2022-06-24 at 13 59 01 | Screenshot 2022-06-24 at 14 05 15 ||
| Screenshot 2022-06-24 at 13 59 07 | Screenshot 2022-06-24 at 14 05 21 ||
| Screenshot 2022-06-24 at 13 59 14 | Screenshot 2022-06-24 at 14 01 29 | Screenshot 2022-06-24 at 14 14 20|
| Screenshot 2022-06-24 at 13 59 20 | Screenshot 2022-06-24 at 14 01 34 | Screenshot 2022-06-24 at 14 14 42|
| Screenshot 2022-06-24 at 13 59 46 | Screenshot 2022-06-24 at 14 01 39 | Screenshot 2022-06-24 at 14 14 56|
| Screenshot 2022-06-24 at 13 59 53 | Screenshot 2022-06-24 at 14 01 44 | Screenshot 2022-06-24 at 14 15 10|
| Screenshot 2022-06-24 at 14 00 23 | Screenshot 2022-06-24 at 14 02 11 ||

And by using SwiftUI's `Table`, we even benefit from some sorting capabilities (here lexicographically on the bare JID)!
Screenshot 2022-06-24 at 14 05 40

### CODE REVIEW

**Review by nesium — APPROVED** [review]
Thanks for the extensive visual documentation! 

What would be nice though is if either all settings panes would have the same width or if the window would animate to the new width. I think it animated before but the animation was broken. There was some glitch there.

**Comment by RemiBardon** [comment]
Update: Using it, I find it annoying to have the "Accounts" tab button moving as I click on it (as the window resizes). I'll see what I can do.

**Comment by nesium** [comment]
Better!

**Comment by RemiBardon** [comment]
It would be worthless to take screenshots again, so I won't do it 😌

Basically I:
- Changed the `GroupBoxStyle` so it can have a "constrained" first column width.
  This way all tabs have the same width (which is a bit bigger), and the form is a bit smaller on the "Accounts" tab.
- Fixed the size of the "Morning" and "Evening" selectors, which were a big bigger than the artboards showed.
- Removed `videoInputStreamPath` from `CallsTab.init` so it's created like the other tab views.

**Comment by valeriansaliou** [comment]
This looks perfect, thanks Rémi!

**Pull request merged**
